;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["plugins/advance/components/detail-attr"],{"11f3":function(t,e,n){"use strict";var r=n("e791"),i=n.n(r);i.a},"1cad":function(t,e,n){"use strict";n.r(e);var r=n("d63a"),i=n.n(r);for(var a in r)"default"!==a&&function(t){n.d(e,t,function(){return r[t]})}(a);e["default"]=i.a},c07b:function(t,e,n){"use strict";var r=function(){var t=this,e=t.$createElement;t._self._c},i=[];n.d(e,"a",function(){return r}),n.d(e,"b",function(){return i})},d63a:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=function(){return n.e("components/basic-component/app-iphone-x/app-iphone-x").then(n.bind(null,"7598"))},i={name:"detail-attr",data:function(){return{image_url:""}},props:{height:Number,cover_pic:String,attr:Array,attr_groups:Array,goods_stock:Number,attr_swell_deposit:String,attr_deposit:String,attr_stock:Number,price_member:Number,attr_price:String,level_show:Number,attr_price_member:Number,num:Number,attr_pic_url:String},methods:{close_attr:function(){this.$emit("close_attr",!0)},select_attr:function(t,e){this.$emit("select_attr",t.attr_group_id,e.attr_id)},change_num:function(t){this.$emit("change_num_data",Number(t.detail.value))},add_num:function(){this.$emit("change_num",1)},edd_num:function(){1!==this.num&&this.$emit("change_num",-1)},clickImage:function(){var e=[];this.attr_pic_url?e.push(this.attr_pic_url):e.push(this.image_url),t.previewImage({urls:e})}},mounted:function(){this.attr[0]&&this.attr[0].pic_url?this.image_url=this.attr[0].pic_url:this.image_url=this.cover_pic},components:{"app-iphone-x":r}};e.default=i}).call(this,n("c11b")["default"])},e791:function(t,e,n){},f471:function(t,e,n){"use strict";n.r(e);var r=n("c07b"),i=n("1cad");for(var a in i)"default"!==a&&function(t){n.d(e,t,function(){return i[t]})}(a);n("11f3");var u=n("2877"),c=Object(u["a"])(i["default"],r["a"],r["b"],!1,null,"0df7307c",null);e["default"]=c.exports}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'plugins/advance/components/detail-attr-create-component',
    {
        'plugins/advance/components/detail-attr-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("f471"))
        })
    },
    [['plugins/advance/components/detail-attr-create-component']]
]);                
