;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["plugins/lottery/common-buttom"],{"0e75":function(t,e,n){"use strict";var r=function(){var t=this,e=t.$createElement,n=(t._self._c,Number(96));t.$mp.data=Object.assign({},{$root:{m0:n}})},o=[];n.d(e,"a",function(){return r}),n.d(e,"b",function(){return o})},"2fb3":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=n("2f62");function o(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),n.push.apply(n,r)}return n}function u(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?o(n,!0).forEach(function(e){i(t,e,n[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):o(n).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))})}return t}function i(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var c=function(){return n.e("components/basic-component/app-iphone-x/app-iphone-x").then(n.bind(null,"7598"))},a=function(){return n.e("components/basic-component/app-empty-bottom/app-empty-bottom").then(n.bind(null,"0c06"))},p={name:"common-buttom",components:{appEmptyBottom:a,appIphoneX:c},computed:u({},(0,r.mapState)("gConfig",{iphone:function(t){return t.iphone},iphoneHeight:function(t){return t.iphoneHeight}})),props:{status:{type:String,default:"index"}},data:function(){return{}},methods:{nav1:function(){t.redirectTo({url:"/plugins/lottery/index/index"})},nav2:function(){t.redirectTo({url:"/plugins/lottery/prize/prize"})}}};e.default=p}).call(this,n("c11b")["default"])},"59cae":function(t,e,n){"use strict";var r=n("bf7f"),o=n.n(r);o.a},"5a76":function(t,e,n){"use strict";n.r(e);var r=n("0e75"),o=n("7815");for(var u in o)"default"!==u&&function(t){n.d(e,t,function(){return o[t]})}(u);n("59cae");var i=n("2877"),c=Object(i["a"])(o["default"],r["a"],r["b"],!1,null,"c9593752",null);e["default"]=c.exports},7815:function(t,e,n){"use strict";n.r(e);var r=n("2fb3"),o=n.n(r);for(var u in r)"default"!==u&&function(t){n.d(e,t,function(){return r[t]})}(u);e["default"]=o.a},bf7f:function(t,e,n){}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'plugins/lottery/common-buttom-create-component',
    {
        'plugins/lottery/common-buttom-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("5a76"))
        })
    },
    [['plugins/lottery/common-buttom-create-component']]
]);                
