;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["plugins/gift/components/index/generate-package"],{"0303":function(t,e,n){"use strict";var a=n("a68a"),c=n.n(a);c.a},"20da":function(t,e,n){"use strict";n.r(e);var a=n("b25c"),c=n.n(a);for(var i in a)"default"!==i&&function(t){n.d(e,t,function(){return a[t]})}(i);e["default"]=c.a},8158:function(t,e,n){"use strict";n.r(e);var a=n("cc2c3"),c=n("20da");for(var i in c)"default"!==i&&function(t){n.d(e,t,function(){return c[t]})}(i);n("0303");var r=n("2877"),o=Object(r["a"])(c["default"],a["a"],a["b"],!1,null,"10081d9b",null);e["default"]=o.exports},a68a:function(t,e,n){},b25c:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var a=n("8de3"),c={name:"generate-package",props:{theme:String,totalPrice:String,template_message_captain:Array},computed:{newPrice:function(){return 0===Number(this.totalPrice)?"0.00":this.totalPrice}},methods:{generatePackage:function(e){var n=this;(0,a.push)(e.detail.formId),this.$storage.getStorageSync("GIFT_CART"),this.$storage.getStorageSync("GIFT_CART")&&Array.isArray(this.$storage.getStorageSync("GIFT_CART"))&&this.$storage.getStorageSync("GIFT_CART").length>0?(console.log(this.template_message_captain),this.$subscribe(this.template_message_captain).then(function(t){console.log(t),n.$emit("click")}).catch(function(t){console.log(t),n.$emit("click")})):t.showToast({mask:!0,title:"请选择礼物",icon:"none"})}}};e.default=c}).call(this,n("c11b")["default"])},cc2c3:function(t,e,n){"use strict";var a=function(){var t=this,e=t.$createElement;t._self._c},c=[];n.d(e,"a",function(){return a}),n.d(e,"b",function(){return c})}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'plugins/gift/components/index/generate-package-create-component',
    {
        'plugins/gift/components/index/generate-package-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("8158"))
        })
    },
    [['plugins/gift/components/index/generate-package-create-component']]
]);                
