;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["pages/cats/style-ten"],{"249f":function(t,e,n){},5982:function(t,e,n){"use strict";var i=n("249f"),s=n.n(i);s.a},"64f5":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var i=function(){return n.e("components/page-component/app-category-list/app-category-list").then(n.bind(null,"5d3f"))},s=function(){return n.e("pages/cats/product-list").then(n.bind(null,"5236"))},o=function(){return n.e("pages/cats/goods-list").then(n.bind(null,"cc6d"))},c=function(){return n.e("pages/cats/second-class").then(n.bind(null,"ef6f"))},a=function(){return n.e("components/page-component/app-no-goods/app-no-goods").then(n.bind(null,"8112"))},u={name:"style-ten",components:{"app-category-list":i,"product-list":s,"app-no-goods":a,"goods-list":o,"second-class":c},props:["list","activeIndex","setHeight","goods_list","activeIndexTwo"],methods:{active:function(t,e){this.$emit("requestGoods",t,e),this.$emit("active",t),this.$emit("page")},lower:function(){this.list[this.activeIndex].child.length>0?this.$emit("lower",this.list[this.activeIndex].child[this.activeIndexTwo]):this.$emit("lower",this.list[this.activeIndex])},setNav:function(t,e){this.$emit("setNav",t,e)},attr:function(t,e,n,i){this.$emit("attr",t,e,n,i)},route_advert:function(t){this.$emit("route_advert",t)}}};e.default=u},"8be3":function(t,e,n){"use strict";n.r(e);var i=n("64f5"),s=n.n(i);for(var o in i)"default"!==o&&function(t){n.d(e,t,function(){return i[t]})}(o);e["default"]=s.a},c16d:function(t,e,n){"use strict";var i=function(){var t=this,e=t.$createElement;t._self._c},s=[];n.d(e,"a",function(){return i}),n.d(e,"b",function(){return s})},d3c3:function(t,e,n){"use strict";n.r(e);var i=n("c16d"),s=n("8be3");for(var o in s)"default"!==o&&function(t){n.d(e,t,function(){return s[t]})}(o);n("5982");var c=n("2877"),a=Object(c["a"])(s["default"],i["a"],i["b"],!1,null,"4438f306",null);e["default"]=a.exports}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'pages/cats/style-ten-create-component',
    {
        'pages/cats/style-ten-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("d3c3"))
        })
    },
    [['pages/cats/style-ten-create-component']]
]);                
