;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["plugins/bargain/common-buttom"],{"22e0":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var o=n("2f62");function r(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(t);e&&(o=o.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),n.push.apply(n,o)}return n}function i(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?r(n,!0).forEach(function(e){u(t,e,n[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):r(n).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))})}return t}function u(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var c=function(){return n.e("components/page-component/app-iphonex-bottom/app-iphonex-bottom").then(n.bind(null,"bc3b"))},a=function(){return n.e("components/basic-component/app-iphone-x/app-iphone-x").then(n.bind(null,"7598"))},p=function(){return n.e("components/basic-component/app-empty-bottom/app-empty-bottom").then(n.bind(null,"0c06"))},f={name:"common-buttom",components:{appIphonexBottom:c,appEmptyBottom:p,appIphoneX:a},computed:i({},(0,o.mapState)("gConfig",{iphone:function(t){return t.iphone},iphoneHeight:function(t){return t.iphoneHeight}})),props:{status:{type:String,default:"index"}},data:function(){return{}},methods:{nav1:function(){t.redirectTo({url:"/plugins/bargain/index/index"})},nav2:function(){t.redirectTo({url:"/plugins/bargain/order-list/order-list"})}}};e.default=f}).call(this,n("c11b")["default"])},"2faf":function(t,e,n){"use strict";n.r(e);var o=n("3f81"),r=n("91a1");for(var i in r)"default"!==i&&function(t){n.d(e,t,function(){return r[t]})}(i);n("e475");var u=n("2877"),c=Object(u["a"])(r["default"],o["a"],o["b"],!1,null,"e162b056",null);e["default"]=c.exports},"3f81":function(t,e,n){"use strict";var o=function(){var t=this,e=t.$createElement,n=(t._self._c,Number(96));t.$mp.data=Object.assign({},{$root:{m0:n}})},r=[];n.d(e,"a",function(){return o}),n.d(e,"b",function(){return r})},"91a1":function(t,e,n){"use strict";n.r(e);var o=n("22e0"),r=n.n(o);for(var i in o)"default"!==i&&function(t){n.d(e,t,function(){return o[t]})}(i);e["default"]=r.a},e475:function(t,e,n){"use strict";var o=n("ee47"),r=n.n(o);r.a},ee47:function(t,e,n){}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'plugins/bargain/common-buttom-create-component',
    {
        'plugins/bargain/common-buttom-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("2faf"))
        })
    },
    [['plugins/bargain/common-buttom-create-component']]
]);                
