;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/basic-component/app-rich/components/wxParseTable"],{"0630f":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r={name:"wxParseTable",props:{node:{type:Object,default:function(){return{}}}},data:function(){return{nodes:[]}},mounted:function(){this.nodes=this.loadNode([this.node])},methods:{loadNode:function(t){var e=[],n=!0,r=!1,a=void 0;try{for(var o,u=t[Symbol.iterator]();!(n=(o=u.next()).done);n=!0){var c=o.value;if("element"==c.node){var s={name:c.tag,attrs:{class:c.classStr,style:c.styleStr},children:c.nodes?this.loadNode(c.nodes):[]};e.push(s)}else"text"==c.node&&e.push({type:"text",text:c.text})}}catch(i){r=!0,a=i}finally{try{n||null==u.return||u.return()}finally{if(r)throw a}}return e}}};e.default=r},"3a3b":function(t,e,n){"use strict";var r=function(){var t=this,e=t.$createElement;t._self._c},a=[];n.d(e,"a",function(){return r}),n.d(e,"b",function(){return a})},7194:function(t,e,n){"use strict";n.r(e);var r=n("3a3b"),a=n("dc30");for(var o in a)"default"!==o&&function(t){n.d(e,t,function(){return a[t]})}(o);n("7e94");var u=n("2877"),c=Object(u["a"])(a["default"],r["a"],r["b"],!1,null,null,null);e["default"]=c.exports},"7e94":function(t,e,n){"use strict";var r=n("cae9"),a=n.n(r);a.a},cae9:function(t,e,n){},dc30:function(t,e,n){"use strict";n.r(e);var r=n("0630f"),a=n.n(r);for(var o in r)"default"!==o&&function(t){n.d(e,t,function(){return r[t]})}(o);e["default"]=a.a}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/basic-component/app-rich/components/wxParseTable-create-component',
    {
        'components/basic-component/app-rich/components/wxParseTable-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("7194"))
        })
    },
    [['components/basic-component/app-rich/components/wxParseTable-create-component']]
]);                
