;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/basic-component/app-rich/components/wxParseTemplate0"],{"2a8a":function(e,n,t){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=function(){return t.e("components/basic-component/app-rich/components/wxParseTemplate1").then(t.bind(null,"1c24"))},a=function(){return Promise.all([t.e("common/vendor"),t.e("components/basic-component/app-rich/components/wxParseImg")]).then(t.bind(null,"50a5"))},r=function(){return t.e("components/basic-component/app-rich/components/wxParseVideo").then(t.bind(null,"b9a8"))},c=function(){return t.e("components/basic-component/app-rich/components/wxParseAudio").then(t.bind(null,"d2fa"))},i=function(){return t.e("components/basic-component/app-rich/components/wxParseTable").then(t.bind(null,"7194"))},u={name:"wxParseTemplate0",props:{node:{type:Object,default:function(){return{}}}},components:{wxParseTemplate:o,wxParseImg:a,wxParseVideo:r,wxParseAudio:c,wxParseTable:i},methods:{wxParseATap:function(e,n){var t=n.currentTarget.dataset.href;if(t){var o=this.$parent;while(!o.preview||"function"!==typeof o.preview)o=o.$parent;o.navigate(t,n,e)}}}};n.default=u},8085:function(e,n,t){"use strict";t.r(n);var o=t("b3ee"),a=t("f75e");for(var r in a)"default"!==r&&function(e){t.d(n,e,function(){return a[e]})}(r);var c=t("2877"),i=Object(c["a"])(a["default"],o["a"],o["b"],!1,null,null,null);n["default"]=i.exports},b3ee:function(e,n,t){"use strict";var o=function(){var e=this,n=e.$createElement;e._self._c},a=[];t.d(n,"a",function(){return o}),t.d(n,"b",function(){return a})},f75e:function(e,n,t){"use strict";t.r(n);var o=t("2a8a"),a=t.n(o);for(var r in o)"default"!==r&&function(e){t.d(n,e,function(){return o[e]})}(r);n["default"]=a.a}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/basic-component/app-rich/components/wxParseTemplate0-create-component',
    {
        'components/basic-component/app-rich/components/wxParseTemplate0-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("8085"))
        })
    },
    [['components/basic-component/app-rich/components/wxParseTemplate0-create-component']]
]);                
