;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/basic-component/app-rich/components/wxParseImg"],{"135a":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=n("2f62");function i(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),n.push.apply(n,r)}return n}function a(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?i(n,!0).forEach(function(e){o(t,e,n[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):i(n).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))})}return t}function o(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var c={name:"wxParseImg",data:function(){return{style:"",preview:!0}},mounted:function(){},props:{node:{type:Object,default:function(){return{}}}},computed:a({newStyleStr:function(){return this.style}},(0,r.mapState)("gConfig",{windowWidth:function(t){return t.imageWidth}}),{newNode:function(){return this.node}}),methods:{wxParseImgTap:function(t){if(this.preview){var e=t.currentTarget.dataset.src;if(e){var n=this.$parent;while(!n.preview||"function"!==typeof n.preview)n=n.$parent;n.preview(e,t)}}},wxParseImgLoad:function(t){var e=this,n=t.currentTarget.dataset.src;if(n){var r=t.mp.detail,i=r.width,a=r.height,o=this.wxAutoImageCal(i,a),c=o.imageheight,u=o.imageWidth,f=this.newNode.attr,s=f.padding,p=f.mode,d=this.newNode.styleStr,h="widthFix"===p?"":"height: ".concat(c,"px;");this.$nextTick().then(function(){e.style="".concat(d||null,"; ").concat(h,"; width: ").concat(u,"; padding: 0 ").concat(+s,"px;display:block;")})}},wxAutoImageCal:function(t,e){var n=this.windowWidth,r={};if(t<60||e<60){var i=this.newNode.attr.src,a=this.$parent;while(!a.preview||"function"!==typeof a.preview)a=a.$parent;a.removeImageUrl(i),this.preview=!1}return r.imageWidth=t,r.imageheight=e,t>n?(r.imageWidth="100%",r.imageheight=n*(e/t)):(r.imageWidth="".concat(t,"px"),r.imageheight=e),r}}};e.default=c},"156b":function(t,e,n){"use strict";var r=n("4739"),i=n.n(r);i.a},"444b":function(t,e,n){"use strict";var r=function(){var t=this,e=t.$createElement;t._self._c},i=[];n.d(e,"a",function(){return r}),n.d(e,"b",function(){return i})},4739:function(t,e,n){},"50a5":function(t,e,n){"use strict";n.r(e);var r=n("444b"),i=n("93a7");for(var a in i)"default"!==a&&function(t){n.d(e,t,function(){return i[t]})}(a);n("156b");var o=n("2877"),c=Object(o["a"])(i["default"],r["a"],r["b"],!1,null,null,null);e["default"]=c.exports},"93a7":function(t,e,n){"use strict";n.r(e);var r=n("135a"),i=n.n(r);for(var a in r)"default"!==a&&function(t){n.d(e,t,function(){return r[t]})}(a);e["default"]=i.a}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/basic-component/app-rich/components/wxParseImg-create-component',
    {
        'components/basic-component/app-rich/components/wxParseImg-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("50a5"))
        })
    },
    [['components/basic-component/app-rich/components/wxParseImg-create-component']]
]);                
