;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/page-component/app-swiper/swiper"],{"4ec4":function(t,e,i){"use strict";var n=i("9a20"),a=i.n(n);a.a},8486:function(t,e,i){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n=a(i("7ab7"));function a(t){return t&&t.__esModule?t:{default:t}}var r={name:"bw-swiper",props:{mode:{type:String,default:"scaleToFill"},swiperHeight:{type:Number,default:350},fullScreen:{type:Boolean,default:!1},swiperList:{type:Array,default:function(){return[]}},swiperType:{type:Boolean,default:!1},videoAutoplay:{type:Boolean,default:!1},videoKey:{type:String,default:"src"},imageKey:{type:String,default:"img"},skipHiddenItemLayout:{type:Boolean,default:!1},displayMultipleItems:{type:Number,default:1},nextMargin:{type:String,default:"0px"},previousMargin:{type:String,default:"0px"},vertical:{type:Boolean,default:!1},circular:{type:Boolean,default:!0},duration:{type:Number,default:400},interval:{type:Number,default:2500},current:{type:Number,default:0},autoplay:{type:Boolean,default:!0},indicatorColor:{type:String,default:"#CCCCCC"},indicatorActiveColor:{type:String,default:"#ffffff"},indicatorDots:{type:Boolean,default:!0}},data:function(){return{flag:!0,cardCur:0}},methods:{play:function(){this.flag=!1},pause:function(){this.flag=!0},clickItem:function(t){console.log(t),this.swiperList.length>0&&((0,n.default)({open_type:this.swiperList[t].open_type,params:this.swiperList[t].params,page_url:this.swiperList[t].page_url}),this.$emit("clickItem",this.swiperList[t]))},change:function(t){this.$emit("change",t)},animationfinish:function(t){this.cardCur=t.detail.current,this.$emit("animationfinish",t)}}};e.default=r},"9a20":function(t,e,i){},b6b4:function(t,e,i){"use strict";i.r(e);var n=i("c032"),a=i("fbbc");for(var r in a)"default"!==r&&function(t){i.d(e,t,function(){return a[t]})}(r);i("4ec4");var u=i("2877"),l=Object(u["a"])(a["default"],n["a"],n["b"],!1,null,null,null);e["default"]=l.exports},c032:function(t,e,i){"use strict";var n=function(){var t=this,e=t.$createElement;t._self._c},a=[];i.d(e,"a",function(){return n}),i.d(e,"b",function(){return a})},fbbc:function(t,e,i){"use strict";i.r(e);var n=i("8486"),a=i.n(n);for(var r in n)"default"!==r&&function(t){i.d(e,t,function(){return n[t]})}(r);e["default"]=a.a}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/page-component/app-swiper/swiper-create-component',
    {
        'components/page-component/app-swiper/swiper-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("b6b4"))
        })
    },
    [['components/page-component/app-swiper/swiper-create-component']]
]);                
