;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/page-component/app-sup-vip/app-sup-vip"],{"288e":function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var r=n("2f62");function u(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter(function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable})),n.push.apply(n,r)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?u(n,!0).forEach(function(t){o(e,t,n[t])}):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):u(n).forEach(function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))})}return e}function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}var a={name:"app-sup-vip",props:{discount:{type:String,default:function(){return null}},is_vip_card_user:{type:Number,default:function(){return 0}},margin:{type:String,default:function(){return"0"}}},data:function(){return{is_show:!1}},created:function(){var e=this;1==e.is_vip_card_user?"1"==e.mall.setting.is_show_super_vip?e.is_show=!0:e.is_show=!1:"1"==e.mall.setting.is_show_normal_vip?e.is_show=!0:e.is_show=!1},computed:i({},(0,r.mapState)({mall:function(e){return e.mallConfig.mall},userInfo:function(e){return e.user.info}}))};t.default=a},2910:function(e,t,n){"use strict";var r=function(){var e=this,t=e.$createElement;e._self._c},u=[];n.d(t,"a",function(){return r}),n.d(t,"b",function(){return u})},"348c":function(e,t,n){"use strict";n.r(t);var r=n("2910"),u=n("43ea");for(var i in u)"default"!==i&&function(e){n.d(t,e,function(){return u[e]})}(i);n("7237");var o=n("2877"),a=Object(o["a"])(u["default"],r["a"],r["b"],!1,null,"847d4af0",null);t["default"]=a.exports},"43ea":function(e,t,n){"use strict";n.r(t);var r=n("288e"),u=n.n(r);for(var i in r)"default"!==i&&function(e){n.d(t,e,function(){return r[e]})}(i);t["default"]=u.a},"649e":function(e,t,n){},7237:function(e,t,n){"use strict";var r=n("649e"),u=n.n(r);u.a}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/page-component/app-sup-vip/app-sup-vip-create-component',
    {
        'components/page-component/app-sup-vip/app-sup-vip-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("348c"))
        })
    },
    [['components/page-component/app-sup-vip/app-sup-vip-create-component']]
]);                
