;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["components/page-component/app-video/app-video"],{2863:function(t,e,n){"use strict";var r=n("98e8"),i=n.n(r);i.a},"3f9d":function(t,e,n){"use strict";var r=function(){var t=this,e=t.$createElement;t._self._c},i=[];n.d(e,"a",function(){return r}),n.d(e,"b",function(){return i})},"48b6":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=u(n("9d0f"));function i(){if("function"!==typeof WeakMap)return null;var t=new WeakMap;return i=function(){return t},t}function u(t){if(t&&t.__esModule)return t;var e=i();if(e&&e.has(t))return e.get(t);var n={};if(null!=t){var r=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var u in t)if(Object.prototype.hasOwnProperty.call(t,u)){var o=r?Object.getOwnPropertyDescriptor(t,u):null;o&&(o.get||o.set)?Object.defineProperty(n,u,o):n[u]=t[u]}}return n.default=t,e&&e.set(t,n),n}var o={name:"app-video",data:function(){return{start:!1,fullScreen:!1}},props:{picUrl:{type:String,default:function(){return""}},url:{type:String,default:function(){return""}},width:{type:String,default:function(){return"750rpx"}},height:{type:String,default:function(){return"422rpx"}}},methods:{fullscreenChange:function(t){this.fullScreen=t.detail.fullScreen},play:function(){var t=this;this.$nextTick().then(function(){t.start=!0}),r.trigger(this.$const.EVENT_VIDEO_END),this.$emit("videoStart",!0),r.on(this.$const.EVENT_VIDEO_END,!0).then(function(){t.start=!1,t.$emit("videoStart",!1)})},autoEnd:function(){var e=this;if(this.start&&!this.fullScreen){var n=t.getSystemInfoSync().windowHeight,i=null;i=t.createSelectorQuery(),i.select(".video").boundingClientRect(),i.selectViewport().scrollOffset(),i.exec(function(t){(t[0].top<=-200||t[0].top>=n-57)&&r.trigger(e.$const.EVENT_VIDEO_END)})}}},computed:{scrollTop:function(){return this.$store.state.page.scrollTop}},watch:{scrollTop:{handler:function(t){this.autoEnd()},immediate:!0}}};e.default=o}).call(this,n("c11b")["default"])},"98e8":function(t,e,n){},d824:function(t,e,n){"use strict";n.r(e);var r=n("3f9d"),i=n("f1a9");for(var u in i)"default"!==u&&function(t){n.d(e,t,function(){return i[t]})}(u);n("2863");var o=n("2877"),c=Object(o["a"])(i["default"],r["a"],r["b"],!1,null,"575578c9",null);e["default"]=c.exports},f1a9:function(t,e,n){"use strict";n.r(e);var r=n("48b6"),i=n.n(r);for(var u in r)"default"!==u&&function(t){n.d(e,t,function(){return r[t]})}(u);e["default"]=i.a}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'components/page-component/app-video/app-video-create-component',
    {
        'components/page-component/app-video/app-video-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("d824"))
        })
    },
    [['components/page-component/app-video/app-video-create-component']]
]);                
