;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["plugins/stock/components/app-index/app-index"],{"0a01":function(t,e,n){"use strict";var a=function(){var t=this,e=t.$createElement;t._self._c},i=[];n.d(e,"a",function(){return a}),n.d(e,"b",function(){return i})},"16cd":function(t,e,n){"use strict";var a=n("19c8"),i=n.n(a);i.a},"19c8":function(t,e,n){},"4bed":function(t,e,n){"use strict";n.r(e);var a=n("df49"),i=n.n(a);for(var o in a)"default"!==o&&function(t){n.d(e,t,function(){return a[t]})}(o);e["default"]=i.a},bf91:function(t,e,n){"use strict";n.r(e);var a=n("0a01"),i=n("4bed");for(var o in i)"default"!==o&&function(t){n.d(e,t,function(){return i[t]})}(o);n("16cd");var r=n("2877"),c=Object(r["a"])(i["default"],a["a"],a["b"],!1,null,"3ee7be6e",null);e["default"]=c.exports},df49:function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var a=n("2f62");function i(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(t);e&&(a=a.filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable})),n.push.apply(n,a)}return n}function o(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?i(n,!0).forEach(function(e){r(t,e,n[e])}):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):i(n).forEach(function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))})}return t}function r(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var c={name:"app-index",props:{detail:{type:Object},setting:{type:Object}},computed:o({},(0,a.mapState)({stock:function(t){return t.mallConfig.__wxapp_img.stock}})),methods:{toUpdate:function(){t.navigateTo({url:"/plugins/stock/update/update"})},toCash:function(){t.navigateTo({url:"/plugins/stock/cash/cash"})},toBonus:function(){var e=this.setting.form.stock?this.setting.form.stock:"",n=this.setting.form.cash_detail?this.setting.form.cash_detail:"";t.navigateTo({url:"/plugins/stock/bonus/bonus?name="+e+"&cash_detail="+n})},toDetail:function(){var e=this.setting.form.cash_detail?this.setting.form.cash_detail:"";t.navigateTo({url:"/plugins/stock/cash-detail/cash-detail?name="+e})},toBalance:function(){var e=this.setting.form.balance_detail?this.setting.form.balance_detail:"";t.navigateTo({url:"/plugins/stock/balance/balance?name="+e})},toAbout:function(){t.navigateTo({url:"/plugins/stock/about/about"})}},creatd:function(t){}};e.default=c}).call(this,n("c11b")["default"])}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'plugins/stock/components/app-index/app-index-create-component',
    {
        'plugins/stock/components/app-index/app-index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("bf91"))
        })
    },
    [['plugins/stock/components/app-index/app-index-create-component']]
]);                
